---
baseurl: https://forestry.io/docs/
languagecode: en-us
pluralizelisttitles: false
theme: forestry-doc-theme
title: Forestry Docs
menu:
  main:
  - name: Blog
    url: http://forestry.io/blog
    weight: 3
  - name: Docs
    url: http://forestry.io/docs/
    weight: 2
  - name: Pricing
    url: http://forestry.io/plans/
    weight: 1
  footer:
  - name: Sitemap
    url: "/all/"
    weight: 4
  - name: Careers
    url: http://forestry.io/careers/
    weight: 3
  - name: Privacy
    url: http://forestry.io/privacy/
    weight: 2
  - name: Terms
    url: http://forestry.io/terms/
    weight: 1
params:
  author:
  - bio: CEO and Co-founder of <a href='https://forestry.io' title='Forestry.io CMS'>Forestry.io</a>.
      Web developer, recovering freelancer.
    img: "/images/Scott_Gallant.jpg"
    link: https://twitter.com/scottgallant
    name: Scott Gallant
    twitter: https://twitter.com/scottgallant
  description: A Static Site CMS for Hugo and Jekyll
  menuweights:
    getting-started: 0
    managing-content: 1
    site-configuration: 2
    developing-with-jekyll: 3
    developing-with-hugo: 4
    deployment-and-management: 5
    troubleshooting: 6
    billing: 7
  twitter_card: https://forestry.io/assets/images/twitter_card_default.png
sitemap:
  ChangeFreq: ''
  Filename: sitemap.xml
  Priority: "-1"
permalinks:
  other: "/:filename"
